### ISSUE TITLE
Login Method Stopped Working

### ISSUE THREAD

**Issue by RyanMulready** [LavaToaster/PHP-Xbox.com-scraper#1]
I've used your code as a base for grabbing data behind a windows live login for some time now but this past weekend it stopped working.

I've got all the post variables coming across correctly but it seems MS added something extra I am missing.  Would love an update to this script with a working login method.

**Comment by LavaToaster** [comment]
Last time I checked someone reported this as broken to me, did you make any changes to it to make it work again?

**Comment by RyanMulready** [comment]
I can't speak on the part that pulls the actual info, the login method worked up until this week without any modification.

**Comment by LavaToaster** [comment]
This should have fixed your issue, if not come back and tell me :smile: 

Also would you mind sharing the site that this is in use on? I would really like to see it.

**Comment by RyanMulready** [comment]
Word, I've updated and modified to fit my needs, I also ran into a problem where I was calling the class from a different directory after an include and the cookie file wasn't being picked up.  I had to hard code the directory the cookie file was pointing at.

The site is http://www.outcastreborn.com; we use a heavily modified version of the code in a number of places.  Appreciate the help.
