### ISSUE TITLE
Login method no longer works

### ISSUE THREAD

**Issue by sc6** [LavaToaster/PHP-Xbox.com-scraper#2]
Hi,

I wanted to let you know that the login method no longer works. I tried to fix it myself, but I've come into some problems trying to fix it.

Awesome repo, by the way. I have it starred.

**Comment by LavaToaster** [comment]
Hi Steve,

Unfortunately this is a really old project of mine, I'm no longer maintaining this. There may be others out there, so hopefully you'll find a replacement.
